### ISSUE TITLE
Problems found in ERPNext V7

### ISSUE THREAD

**Issue by rtimagine** [saguas/frappe_base_vat#2]
Hi there,

I have found problems after upgrading to V7. I even uninstall and reinstalled the base_vat but problems are still there. Is all related when you add a Customer in the Doctypes. For instance, it happens if you add a Customer in a Project.

Here is a trace of the error:

Traceback (most recent call last):
  File "/home/varmys/frappe-bench/apps/frappe/frappe/app.py", line 55, in application
    response = frappe.handler.handle()
  File "/home/varmys/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/varmys/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, *_frappe.form_dict)
  File "/home/varmys/frappe-bench/apps/frappe/frappe/**init**.py", line 879, in call
    return fn(_args, *_newargs)
  File "/home/varmys/frappe-bench/apps/frappe/frappe/desk/form/load.py", line 51, in getdoc
    doc.add_seen()
  File "/home/varmys/frappe-bench/apps/frappe/frappe/model/document.py", line 931, in add_seen
    self.db_set('_seen', json.dumps(_seen), update_modified=False)
  File "/home/varmys/frappe-bench/apps/frappe/frappe/model/base_document.py", line 362, in db_set
    self.run_method('on_change')
  File "/home/varmys/frappe-bench/apps/frappe/frappe/model/document.py", line 661, in run_method
    return Document.hook(fn)(self, *args, *_kwargs)
  File "/home/varmys/frappe-bench/apps/frappe/frappe/model/document.py", line 839, in composer
    return composed(self, method, _args, *_kwargs)
  File "/home/varmys/frappe-bench/apps/frappe/frappe/model/document.py", line 824, in runner
    add_to_return_value(self, f(self, method, _args, *_kwargs))
  File "/home/varmys/frappe-bench/apps/erpnext/erpnext/accounts/party_status.py", line 52, in notify_status
    party.save(ignore_permissions=True)
  File "/home/varmys/frappe-bench/apps/frappe/frappe/model/document.py", line 242, in save
    return self._save(_args, *_kwargs)
  File "/home/varmys/frappe-bench/apps/frappe/frappe/model/document.py", line 269, in _save
    self.run_before_save_methods()
  File "/home/varmys/frappe-bench/apps/frappe/frappe/model/document.py", line 710, in run_before_save_methods
    self.run_method("validate")
  File "/home/varmys/frappe-bench/apps/frappe/frappe/model/document.py", line 661, in run_method
    return Document.hook(fn)(self, _args, *_kwargs)
  File "/home/varmys/frappe-bench/apps/frappe/frappe/model/document.py", line 836, in composer
    hooks.append(frappe.get_attr(handler))
  File "/home/varmys/frappe-bench/apps/frappe/frappe/__init__.py", line 859, in get_attr
    return getattr(get_module(modulename), methodname)
  File "/home/varmys/frappe-bench/apps/frappe/frappe/**init**.py", line 643, in get_module
    return importlib.import_module(modulename)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/home/varmys/frappe-bench/apps/base_vat/base_vat/vat/vat_validation.py", line 12, in 
    _logger = frappe.get_logger(__name__)
AttributeError: 'module' object has no attribute 'get_logger'

Kind Regards,

Rubén

**Comment by saguas** [comment]
Thanks for your report!
Please update. I think it is fix it now.
Let me know if you find more errors.
Luís Fernandes.
